### ISSUE TITLE
fix: eliminate circular import between database/models and observability/tracking

### ISSUE THREAD

**Issue by gtpooniwala** [gtpooniwala/personal-agent#144]
## Problem

A circular import exists between the database and observability layers:

```
backend/database/models.py
  → backend/runtime/__init__.py                    (imports ConversationMaintenanceService)
  → backend/runtime/conversation_maintenance.py    (imports backend.observability)
  → backend/observability/__init__.py              (imports tracking)
  → backend/observability/tracking.py              (imports db_ops from database.operations)
  → backend/database/operations.py                 (imports from database/models.py)
  → 💥 circular ImportError
```

This caused Docker containers to crash on startup with:

```
ImportError: cannot import name 'Base' from partially initialized module
'backend.database.models' (most likely due to a circular import)
```

The cycle was introduced by e03dd69 (#141) which added `ConversationMaintenanceService` to `runtime/__init__.py` — connecting the runtime layer (which imports observability) to a module already in the observability → database chain.

## Temporary Fix (PR #126 / commit 7da361a)

Deferred the `ConversationMaintenanceService` import in `runtime/__init__.py` using Python's PEP 562 `__getattr__` hook:

```python
# runtime/__init__.py
def __getattr__(name: str):
    if name == "ConversationMaintenanceService":
        from .conversation_maintenance import ConversationMaintenanceService
        return ConversationMaintenanceService
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
```

This is production-safe (legitimate Python 3.7+ pattern) and does not break any test patching, but it treats the symptom rather than the structural cause.

## Permanent Fix

The root issue is that `database/models.py` imports `RUN_EVENT_TYPES` and `RUN_STATUSES` from `backend.runtime`, triggering the full runtime package init. These are just string constants and do not need to come from the runtime package.

**Recommended fix (Option A):** `database/models.py` should import directly from `backend.runtime.lifecycle` (which already defines these constants) without going through the runtime package `__init__`. The trick is that Python still runs the package `__init__` when loading any submodule, so this alone is not enough — the `__getattr__` workaround would still be needed unless the constants are moved below the runtime package entirely (e.g. `backend/runtime/constants.py` or `backend/constants.py` with no upward deps).

**Alternative (Option B):** Decouple `observability/tracking.py` from `database.operations` by injecting `db_ops` rather than importing it at module level, removing the observability → database dependency entirely.

Option B is the cleaner architectural fix: observability should not depend on the database layer.

## Files Involved

- `backend/database/models.py` — imports `RUN_EVENT_TYPES`, `RUN_STATUSES` from `backend.runtime`
- `backend/runtime/__init__.py` — temporary `__getattr__` workaround lives here
- `backend/runtime/lifecycle.py` — already defines the constants
- `backend/observability/tracking.py` — imports `db_ops` at module level, the other end of the chain
